### ISSUE TITLE
Issues with .NET Standard reference on Linux starting with 2020.9.1

### ISSUE THREAD

**Issue by Kaliumhexacyanoferrat** [adoconnection/RazorEngineCore#34]
After updating to version `2020.9.1`, I get the following exception when [rendering templates](https://github.com/Kaliumhexacyanoferrat/GenHTTP/blob/dependabot/nuget/RazorEngineCore-2020.9.1/Modules/Razor/Providers/RazorRenderer.cs):

> RazorEngineCore.RazorEngineCompilationException: Unable to compile template: (28,29): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at RazorEngineCore.RazorEngine.CreateAndCompileToStream(String templateSource, RazorEngineCompilationOptions options)
   at RazorEngineCore.RazorEngine.Compile[T](String content, Action`1 builderAction)

This happens on Linux only (see [this build](https://github.com/Kaliumhexacyanoferrat/GenHTTP/pull/102/checks?check_run_id=1214939632)), the same logic works on Windows as expected (with identical SDK versions etc.).

Do you have an idea how to overcome this issue? I tried to tweak the assembly references, but I suspect the compilation process of the template is missing some .NET Standard reference.

**Comment by adoconnection** [comment]
Hi, thats probably due to I missed something with references on init. Will recheck it again.

**Comment by adoconnection** [comment]
did it work on 2020.6.1? 
there was a pull request do remove netstadrard reference if under linux and it never changed from that time (as I can see)
 https://github.com/adoconnection/RazorEngineCore/commit/7975beb8035d3ef8b0cea79142d56e597510b8c5#diff-da023b3e46c83993108046dee9e55032

However I have the same error as you do. If I return netstandard reference back, the error dissapears. Im confused.

@daghb does 2020.9.1 work for your linux environment?

**Comment by Kaliumhexacyanoferrat** [comment]
@adoconnection: It did work on 2020.6.1. As dependabot creates a PR for the new version, I can rule out changes in the environment (such as the SDK version).

**Comment by adoconnection** [comment]
I have no idea how is this possible :)
here are all the changes, 2020.6.1 - is July version
https://github.com/adoconnection/RazorEngineCore/commits/master/RazorEngineCore/RazorEngineCompilationOptions.cs

**Comment by Kaliumhexacyanoferrat** [comment]
I can have a look later on - what does `RuntimeInformation.FrameworkDescription` evaluate to in you Linux environment? 🤔

**Comment by adoconnection** [comment]
ok, the mystery revealed. 2020.6.1 relese had "wrong code" 
![image](https://user-images.githubusercontent.com/499855/95749567-6db9e000-0ca4-11eb-9d9a-9d18a0cc9083.png)

**Comment by Kaliumhexacyanoferrat** [comment]
Build with 2020.10.1 works on Windows and Linux. Thank you very much!
